### ISSUE TITLE
Emulator will load but wont start

### ISSUE THREAD

**Issue by DeloWeather** [qconrad/intellistar-emulator#19]
I opened the emulator typed in zip pressed start button but didn't respond because its been working great this whole time

**Comment by qconrad** [comment]
Thanks for the report. Unfortunately, this is due to the [discontinuation of Weather Underground API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api). Most of the emulator runs off the Weather Channel's API now but severe weather alerts, radar imagery, and zip code geolookup still rely on this no longer existant API. Because of this I temporarily removed these features so that it will still run. I'm not sure when they will be working again but you should at least be able to run it now.

**Comment by DeloWeather** [comment]
Thanks for the update!!

**Comment by FNCxPro** [comment]
I may be able to push changes that fix this tomorrow
