### ISSUE TITLE
Loop parameter wont work

### ISSUE THREAD

**Issue by papercore-dev** [qconrad/intellistar-emulator#28]
loop: true
was set up in config.js but no luck, it wont work.

**Comment by qconrad** [comment]
Thanks for the report. I never tried setting from the config file because you can click the weather channel logo to toggle. This is fixed now but the config file is never overwritten by the software. This means you couldn't enable looping in the config file and disable it by clicking the logo for example. If either are enabled, it will loop so it's best to only use one method (config file or logo) for enabling it. Perhaps this could be made less ambiguous at a later date.
