### ISSUE TITLE
Suggestion: re-implementing the basic narrations

### ISSUE THREAD

**Issue by DDroid** [qconrad/intellistar-emulator#8]
Is it possible that we could have a setting on the main screen, to enable or disable the basic narrations (for reading temperature, conditions and slides)? I know that the narrations we're quite basic, however if the option is given to enable or disable them, the user can choose to use them or not, instead of having to go to the trouble of adding all the removed script lines back manually. 

If we wanted to take it a step more, there could even be a setting added for *experimental* narrations (such as narrating the forecast in a very basic fashion, untill more narrations can be found. I do have the "High" and "Low" narrations for a start.)

**Comment by FNCxPro** [comment]
@DDroid I'll look into implementing them again and making them up to standards with what @qconrad wants them to be. I believe one of the issues that he might've faced would be the narration for the current condition would be wrong, since I never looked into it after implementing the official TWC weather API into the emulator.

If you could let me know about it @qconrad that would be appreciated :)

**Comment by qconrad** [comment]
The reason they broke was the condition lookup table that used the weather underground API to match conditions to condition narrations. In order to work, this has to be updated for the new API. The main problem with how they were implemented before was that they narration audio files were loaded as they were needed. This resulted in pauses between them and a lot of times they just wouldn't even play. Ideally, all the narrations needed for the forecast should be loaded at the start.
